carce:
  prefix: https://cloud.carce.cc
  webUrl: https://sale.carce.cc
  ftp:
    server: 125.227.138.209
    port: 21
    user: cloud
    password: 7b2s2Oh&5
spring:
  datasource:
    carcecloud:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://192.168.42.209:3306/carce_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: cloud
      password: "cV2ws835!"
