carce:
  prefix: https://testcloud.carce.cc
  webUrl: http://localhost:8080
  ftp:
    server: 125.227.138.209
    port: 21
    user: testcloud
    password: x32*9oFb6
spring:
  datasource:
    carcecloud:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3316/test_carce_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
