carce:
  prefix: https://testcloud.carce.cc
  webUrl: https://sale.carce.cc
  ftp:
    server: 125.227.138.209
    port: 21
    user: testcloud
    password: x32*9oFb6
ruoyi:
  profile: /home/jimmy/car_files
spring:
  datasource:
    carcecloud:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://192.168.42.209:3306/test_carce_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: test_cloud
      password: "oP9m7_2h"
