carce:
  prefix: https://testcloud.carce.cc
  webUrl: https://sale.carce.cc/
  ftp:
    server: 125.227.138.209
    port: 21
    user: testcloud
    password: x32*9oFb6
ruoyi:
  profile: /home/jimmy/car_files
spring:
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://192.168.42.209:3306/sale?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: sale_carce
      password: "UExg1u8fxJ@*2qup"
    carcecloud:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://192.168.42.209:3306/test_carce_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: test_cloud
      password: "oP9m7_2h"
    initialSize: 5
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    maxEvictableIdleTimeMillis: 900000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    webStatFilter:
      enabled: true
    statViewServlet:
      enabled: true
      allow: null
      url-pattern: /druid/*
      login-username: ruoyi
      login-password: 123456
    filter:
      stat:
        enabled: true
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true
  redis:
    host: 192.168.0.112
    port: 6379
    database: 0
    password: null
